{"name": "test_consult_failure_evidence", "status": "passed", "description": "\n        P2 #11: Consultar evidencia del fallo\n        ", "start": 1760549957968, "stop": 1760549968545, "uuid": "8345db35-4f78-41b1-b1d4-c3dd2e4c3146", "historyId": "47986703edd062e88f4248f914968db9", "testCaseId": "47986703edd062e88f4248f914968db9", "fullName": "tests.test_notifications.TestNotifications#test_consult_failure_evidence", "labels": [{"name": "tag", "value": "test_id('P2-011')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_notifications"}, {"name": "subSuite", "value": "TestNotifications"}, {"name": "host", "value": "L43429"}, {"name": "thread", "value": "10972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_notifications"}]}