{"name": "test_consult_failure_evidence", "status": "passed", "description": "\n        P2 #11: Consultar evidencia del fallo\n        ", "start": 1760553145493, "stop": 1760553155321, "uuid": "59b2d9f7-b3ee-45b1-986e-80981b43dfe2", "historyId": "47986703edd062e88f4248f914968db9", "testCaseId": "47986703edd062e88f4248f914968db9", "fullName": "tests.test_notifications.TestNotifications#test_consult_failure_evidence", "labels": [{"name": "tag", "value": "test_id('P2-011')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_notifications"}, {"name": "subSuite", "value": "TestNotifications"}, {"name": "host", "value": "L43429"}, {"name": "thread", "value": "11072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_notifications"}]}