{"name": "test_consult_failure_evidence", "status": "passed", "description": "\n        P2 #11: Consultar evidencia del fallo\n        ", "start": 1760553986233, "stop": 1760553999388, "uuid": "c253726a-7c8b-4dcf-be37-0849d9abfe09", "historyId": "47986703edd062e88f4248f914968db9", "testCaseId": "47986703edd062e88f4248f914968db9", "fullName": "tests.test_notifications.TestNotifications#test_consult_failure_evidence", "labels": [{"name": "tag", "value": "test_id('P2-011')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_notifications"}, {"name": "subSuite", "value": "TestNotifications"}, {"name": "host", "value": "L43429"}, {"name": "thread", "value": "5772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_notifications"}]}