{"name": "test_receive_failure_notification", "status": "failed", "statusDetails": {"message": "Failed: ScopeMismatch: You tried to access the function scoped fixture base_url with a session scoped request object, involved factories:\n.venv\\Lib\\site-packages\\pytest_base_url\\plugin.py:18:  def _verify_url(request, base_url)\ntests\\conftest.py:29:  def base_url()", "trace": "ScopeMismatch: You tried to access the function scoped fixture base_url with a session scoped request object, involved factories:\n.venv\\Lib\\site-packages\\pytest_base_url\\plugin.py:18:  def _verify_url(request, base_url)\ntests\\conftest.py:29:  def base_url()"}, "description": "\n        P2 #1: Recibir notificaci√≥n cuando falla la entrega\n        ", "start": 1760549902765, "stop": 1760549902765, "uuid": "eb02fb50-f509-4bc1-84e8-4d11aaf71e21", "historyId": "680553b39e3df9464fa6b21a7c09dc19", "testCaseId": "680553b39e3df9464fa6b21a7c09dc19", "fullName": "tests.test_notifications.TestNotifications#test_receive_failure_notification", "labels": [{"name": "tag", "value": "test_id('P2-001')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_notifications"}, {"name": "subSuite", "value": "TestNotifications"}, {"name": "host", "value": "L43429"}, {"name": "thread", "value": "17604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_notifications"}]}