{"name": "test_consult_failure_evidence", "status": "passed", "description": "\n        P2 #11: Consultar evidencia del fallo\n        ", "start": 1760550971758, "stop": 1760550981448, "uuid": "a634f24c-7b2c-4922-8f51-48bf47ac1036", "historyId": "47986703edd062e88f4248f914968db9", "testCaseId": "47986703edd062e88f4248f914968db9", "fullName": "tests.test_notifications.TestNotifications#test_consult_failure_evidence", "labels": [{"name": "tag", "value": "test_id('P2-011')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_notifications"}, {"name": "subSuite", "value": "TestNotifications"}, {"name": "host", "value": "L43429"}, {"name": "thread", "value": "17800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_notifications"}]}