{"name": "test_verify_failure_reason_saved", "status": "passed", "description": "\n        Verificar que el motivo de fallo se guarda correctamente\n        ", "start": 1760553263950, "stop": 1760553274342, "uuid": "f767d3cc-1aa7-448d-920e-6cf4e3528d33", "historyId": "efe924dfd0fa933a1042828ca4f40b7f", "testCaseId": "efe924dfd0fa933a1042828ca4f40b7f", "fullName": "tests.test_rider_functionality.TestRiderFunctionality#test_verify_failure_reason_saved", "labels": [{"name": "tag", "value": "test_id('P2-013-VERIFY')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_rider_functionality"}, {"name": "subSuite", "value": "TestRiderFunctionality"}, {"name": "host", "value": "L43429"}, {"name": "thread", "value": "11072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_rider_functionality"}]}